spring.application.name=todo
server.port=8080
server.error.include-stacktrace=ALWAYS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=<your PostgreSQL username>
spring.datasource.password=<your PostgreSQL password>
spring.jpa.show-sql=true